apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  #namespace: default
  labels:
    app: demo-app
    env: staging
spec:
  containers:
  - image: betalabsk8sacr.azurecr.io/ngo/dev:bls1
  #- image: ngol/dev3:bls1
    imagePullPolicy: Always
    resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "300m"
    name: demo-app
#    volumeMounts:
#    - mountPath: "/mnt/azure"
#      name: volume
#  volumes:
#    - name: volume
#      persistentVolumeClaim:
#        claimName: demo-azure-managed-disk
#  tolerations:
#    - key: "kubernetes.azure.com/scalesetpriority"
#      operator: "Equal"
#      value: "spot"
#      effect: "NoSchedule"
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: agentpool
#                operator: In
#                values:
#                  - spotnode
#Secret test---
#    volumeMounts:
#    - mountPath: "/mnt/secret"
#      name: secret
#      readOnly: true
#  volumes:
#    - name: secret
#      secret:
#            secretName: stg-airflow-db-secret



#apiVersion: v1
#kind: Service
#metadata:
#  name: demo
#spec:
#  ports:
#     -  port: 80
#        protocol: TCP
#        targetPort: 80
#  selector:
#    app: demo-app
#  type: NodePort
#
#---
